"""error seeding

Revision ID: d0d6a106cf88
Revises: b9d68a1598ce
Create Date: 2024-03-28 18:19:34.360042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d6a106cf88'
down_revision = 'b9d68a1598ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_admins_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='fk_admin_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admins')
    # ### end Alembic commands ###
